FROM alpine

# Install glibc for CGO compatibility
RUN apk add --no-cache libc6-compat

RUN mkdir /app

# Copy pre-built artifacts based on the platform
ARG TARGETOS
ARG TARGETARCH
COPY ./binaries/$TARGETOS/$TARGETARCH/mqtt-go-playground /app/mqtt-go-playground
RUN chmod +x /app/mqtt-go-playground

# Set up user
RUN addgroup -S umqtt-go-playground && adduser -S umqtt-go-playground -G umqtt-go-playground
RUN chown umqtt-go-playground:umqtt-go-playground /app
USER umqtt-go-playground


CMD ["sh", "-c", "/app/mqtt-go-playground"]
