package dataObjects

// Generated by https://quicktype.io
type DeviceConfigThermostat struct {
	Availability               []Availability `json:"availability"`
	AwayModeCommandTopic       string         `json:"away_mode_command_topic"`
	AwayModeStateTemplate      string         `json:"away_mode_state_template"`
	AwayModeStateTopic         string         `json:"away_mode_state_topic"`
	CurrentTemperatureTemplate string         `json:"current_temperature_template"`
	CurrentTemperatureTopic    string         `json:"current_temperature_topic"`
	Device                     Device         `json:"device"`
	HoldCommandTopic           string         `json:"hold_command_topic"`
	HoldModes                  []string       `json:"hold_modes"`
	HoldStateTemplate          string         `json:"hold_state_template"`
	HoldStateTopic             string         `json:"hold_state_topic"`
	JSONAttributesTopic        string         `json:"json_attributes_topic"`
	MaxTemp                    string         `json:"max_temp"`
	MinTemp                    string         `json:"min_temp"`
	ModeCommandTopic           string         `json:"mode_command_topic"`
	ModeStateTemplate          string         `json:"mode_state_template"`
	ModeStateTopic             string         `json:"mode_state_topic"`
	Modes                      []string       `json:"modes"`
	Name                       string         `json:"name"`
	TempStep                   float64        `json:"temp_step"`
	TemperatureCommandTopic    string         `json:"temperature_command_topic"`
	TemperatureStateTemplate   string         `json:"temperature_state_template"`
	TemperatureStateTopic      string         `json:"temperature_state_topic"`
	TemperatureUnit            string         `json:"temperature_unit"`
	UniqueID                   string         `json:"unique_id"`
	CustomControl              bool           `json:"under_custom_control"`
}
